image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
  - port: 5900
  - port: 6080

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - before: |
    init: |
      echo 'Install fp-compiler ....'

  - init: |
    command: echo '...'

  - command: "firefox https://www.youtube.com/watch?v=D41zSHJthZI"

vscode:
  extensions:
    - alefragnani.delphi-pack@2.0.0:EO4cpgi8xpuCkeL6dEJ4Pg==
